sudo: required
language: bash
before_deploy:
- mkdir -p ~/.ssh && echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config
- chmod 600 aws-dream.pem
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i aws-dream.pem ubuntu@ec2-3-15-210-253.us-east-2.compute.amazonaws.com 'docker-compose --version && cd dreamapp-cd && git pull && pwd && echo "STOP DOCKER COMPOSE" && sudo docker-compose down && echo "START DOCKER COMPOSE" && sudo docker-compose up -d && echo "CHECK DC PS" && sudo docker-compose ps && echo "CHECK DOCKER PS" && sudo docker ps'
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_e591611b5a4a_key -iv $encrypted_e591611b5a4a_iv
  -in aws-dream.pem.enc -out aws-dream.pem -d
