{
 "title": "Dream Dash",
 "description": "Мониторинг Чудо-Сервиса",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "revision", "label": "Версия \\ ревизия процесса", "query": "default" },
   { "name": "userLogin", "label": "Логин пользователя", "query": "admin" }
  ]
 },
 "panels": [
  {
   "title": "Количество процессов, экземпляров",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "totalProcessCompletedCounter{revision=\"$revision\",userLogin=\"$userLogin\"}"
    }
   ]
  },
  {
   "title": "Стоимость процессов, у.е.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_process_cost{revision=\"$revision\",userLogin=\"$userLogin\"}[1m])/rate(totalProcessCompletedCounter{revision=\"$revision\",userLogin=\"$userLogin\"}[1m])"
    }
   ]
  },
  {
   "title": "Длительность процессов, дней",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_process_duration{revision=\"$revision\",userLogin=\"$userLogin\"}[1m])/24/60/rate(totalProcessCompletedCounter{revision=\"$revision\",userLogin=\"$userLogin\"}[1m])"
    }
   ]
  }
 ]
}