{
 "title": "Dream - Operational Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "createAndStartProcess endpoint request count per minute",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"createAndStartProcess\"}[1m]))"
    }
   ]
  },
  {
   "title": "Average requests per minute to createAndStartProcess endpoint",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"createAndStartProcess\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution time quantiles for endpoint createAndStartProcess",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "api_execution_elapsed_nanosecond{endpoint=\"createAndStartProcess\"}"
    }
   ]
  },
  {
   "title": "createAndStartProcess endpoint status code responses per minute",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_http_response_code{endpoint=\"createAndStartProcess\"}[1m])"
    }
   ]
  },
  {
   "title": "Exceptions details (10 minutes)",
   "type": "table",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "increase(api_http_stacktrace_exceptions{endpoint=\"createAndStartProcess\"}[10m])"
    }
   ]
  },
  {
   "title": "Exception count per 10 minutes",
   "type": "stat",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(increase(api_http_stacktrace_exceptions{endpoint=\"createAndStartProcess\"}[10m]))"
    }
   ]
  }
 ]
}