# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'dream-process-app'

    scrape_interval: 10s

    metrics_path: /metrics

    static_configs:
      - targets: ['dream-process-app:8080']
        
        #['host.docker.internal:8180']

  - job_name: 'prometheus-node-exporter'
    static_configs:
      - targets: ['nodeexporter:9100']

#  - job_name: 'prometheus-cadvisor'
#    static_configs:
#      - targets: ['cadvisor:8070']
